python foolbox_test5a.py -a ADefAttack
python foolbox_test5a.py -a AdditiveGaussianNoiseAttack
python foolbox_test5a.py -a AdditiveNoiseAttack
python foolbox_test5a.py -a AdditiveUniformNoiseAttack
python foolbox_test5a.py -a ApproximateLBFGSAttack
python foolbox_test5a.py -a BIM
python foolbox_test5a.py -a BasicIterativeMethod
python foolbox_test5a.py -a BinarizationRefinementAttack
python foolbox_test5a.py -a BlendedUniformNoiseAttack
python foolbox_test5a.py -a BoundaryAttack
python foolbox_test5a.py -a BoundaryAttackPlusPlus
python foolbox_test5a.py -a CarliniWagnerL2Attack
python foolbox_test5a.py -a ContrastReductionAttack
python foolbox_test5a.py -a DecoupledDirectionNormL2Attack
python foolbox_test5a.py -a DeepFoolAttack
python foolbox_test5a.py -a DeepFoolL2Attack
python foolbox_test5a.py -a DeepFoolLinfinityAttack
python foolbox_test5a.py -a EADAttack
python foolbox_test5a.py -a FGSM
python foolbox_test5a.py -a GaussianBlurAttack
python foolbox_test5a.py -a GradientAttack
python foolbox_test5a.py -a GradientSignAttack
python foolbox_test5a.py -a IterativeGradientAttack
python foolbox_test5a.py -a IterativeGradientSignAttack
python foolbox_test5a.py -a L1BasicIterativeAttack
python foolbox_test5a.py -a L2BasicIterativeAttack
python foolbox_test5a.py -a LBFGSAttack
python foolbox_test5a.py -a LinfinityBasicIterativeAttack
python foolbox_test5a.py -a LocalSearchAttack
python foolbox_test5a.py -a MomentumIterativeAttack
python foolbox_test5a.py -a MomentumIterativeMethod
python foolbox_test5a.py -a NewtonFoolAttack
python foolbox_test5a.py -a PGD
python foolbox_test5a.py -a PointwiseAttack
python foolbox_test5a.py -a PrecomputedAdversarialsAttack
python foolbox_test5a.py -a ProjectedGradientDescent
python foolbox_test5a.py -a ProjectedGradientDescentAttack
python foolbox_test5a.py -a RandomPGD
python foolbox_test5a.py -a RandomProjectedGradientDescent
python foolbox_test5a.py -a RandomStartProjectedGradientDescentAttack
python foolbox_test5a.py -a SLSQPAttack
python foolbox_test5a.py -a SaliencyMapAttack
python foolbox_test5a.py -a SaltAndPepperNoiseAttack
python foolbox_test5a.py -a SinglePixelAttack
python foolbox_test5a.py -a SparseFoolAttack
python foolbox_test5a.py -a SpatialAttack
